### PR TITLE
#73: Fixed the touch feedback on iOS

### LINKED ISSUE #73: TouchFeedBackIOS triggers touchdown when 2 TouchFeedBackIOS are on top of each other
We should only allow the top one to scale.

(on click is not triggered so that is already correct)

### PR DESCRIPTION
**Pull request by vanlooverenkoen**
Fixed #73

### CODE REVIEW

**Review by NicolaVerbeeck — APPROVED** [review]

File: lib/src/widget/touch_feedback/touch_feedback.dart [hunk 1]
```diff
@@ -115,7 +125,15 @@ class _TouchFeedBackIOSState extends State<TouchFeedBackIOS> {
   }
 
   void _setTouched(bool touched) {
-    if (widget.onClick == null) return;
+    if (!touched) _touchPoints.remove(_key);
+    if (widget.onClick == null || this.touched == touched) return;
     setState(() => this.touched = touched);
```
Comment (ikbendewilliam) [inline lib/src/widget/touch_feedback/touch_feedback.dart:130]: Should we not remove `_touchPoints[_key]` when touched is set to false?

Comment (ikbendewilliam) [reply lib/src/widget/touch_feedback/touch_feedback.dart:130]: nvm I'm blind

**Review by ikbendewilliam — DISMISSED** [review]

**Review by ikbendewilliam — APPROVED** [review]
